INSERT INTO CUSTOMER (FIRSTNAME, SURNAME, STREET,CITY,STATE,POSTCODE)
    VALUES ('Frank', 'Grimes', '123 Fake St', 'Aislebie', 'VIC', '3220'),
           ('Jane', 'Smith', '21 Green St', 'Belmont', 'NSW', '3216'),
           ('Jimmy', 'James', '3 Apple Way', 'Geelong', 'VIC', '3220'),
           ('Sarah', 'Green', '6 Far St', 'Sale', 'QLD', '3216'),
           ('Karen', 'Baites', '21 Second  St', 'Denton', 'VIC', '2345'),
           ('Robert', 'Burdon', '42 First  St', 'Durham', 'QLD', '4565'),
           ('Scott', 'Bell', '3 Elm  St', 'Elswicke', 'NSW', '7865'),
           ('Steph', 'Benett', '42 Main  St', 'Killom', 'VIC', '3243'),
           ('Craig', 'Bowden', '74 Second  St', 'Langley', 'NSW', '3454'),
           ('David', 'Brasse', '5 Oak  St', 'Durham', 'NT', '4565'),
           ('John', 'Flower', '7 Seventh  St', 'Walworthe', 'VIC', '3841'),
           ('Peter', 'Smith', '3 Elm  St', 'Denton', 'NSW', '7865'),
           ('Marge', 'Gardiner', '4 Eighth  St', 'Winlinton', 'VIC', '6523'),
           ('Alice ', 'Gray', '42 Oak  St', 'Whickham', 'WA', '4523'),
           ('Dorothy', 'Gardiner', '65 Washington  St', 'Togston', 'QLD', '4538'),
           ('Elizabeth', 'Hall', '245 View  St', 'Elswicke', 'NT', '4521'),
           ('Helen', 'Hilton', '35 Main  St', 'Belmont', 'VIC', '3242'),
           ('Grace', 'Hopper', '47 Second  St', 'Sighill', 'SA', '1456'),
           ('Isabell', 'Hutton', '4 Lake  St', 'Whickham', 'WA', '3554'),
           ('Adam', 'Hunter', '3 Eighth  St', 'Seaton', 'QLD', '2874'),
           ('Andrew', 'Flower', '2 Green St', 'Nonstaynton', 'VIC', '6521'),
           ('Alexander', 'Jenison', '7 Washington  St', 'Killom', 'QLD', '3541'),
           ('Charles', 'Lancaster', '543 Elm  St', 'Winlinton', 'VIC', '2452'),
           ('Dean', 'Martin', '35 View  St', 'Denton', 'SA', '1455'),
           ('Francis', 'Lee', '41 Oak  St', 'Langley', 'NSW', '7531'),
           ('George', 'Maire', '74 Park  St', 'Durham', 'VIC', '8753'),
           ('Gerard', 'Marshall', '85 First  St', 'Denton', 'NT', '9543'),
           ('Hector', 'Milbourne', '7 Main  St', 'Elswicke', 'QLD', '5453'),
           ('Henry', 'Morton', '2 Park  St', 'Whickham', 'VIC', '4534'),
           ('James', 'Flower', '6 Washington  St', 'Killom', 'SA', '6842'),
           ('Leonard', 'Percye', '45 Eighth  St', 'Belmont', 'QLD', '8435'),
           ('Jasper', 'Porter', '65 Park  St', 'Winlinton', 'WA', '2354'),
           ('Peter', 'Riddell', '25 Oak  St', 'Durham', 'VIC', '7853'),
           ('Roger', 'Sanderson', '12 Lake  St', 'Walworthe', 'QLD', '3542'),
           ('Janet', 'Spence', '75 Main  St', 'Langley', 'NSW', '2378'),
           ('Margaret', 'Smythe', '4 First  St', 'Elswicke', 'WA', '5373'),
           ('Martha', 'Turner', '65 Seventh  St', 'Denton', 'QLD', '5737'),
           ('Susana', 'Wall', '21 View  St', 'Tudbury', 'VIC', '3573'),
           ('Rebecca', 'Wilson', '45 Lake  St', 'Belmont', 'VIC', '3573'),
           ('Bob', 'Smith', '6 Blue St', 'Highton', 'VIC', '3753')


