CREATE TABLE PARTS
(PARTNUM INT AUTO_INCREMENT PRIMARY KEY,
 PARTNAME CHAR(40),
 DESCRIPTION CHAR(50),
 SPECIFICATIONS CHAR(80),
 ONHAND INT,
 CATEGORY CHAR(40),
 WAREHOUSE CHAR(20),
 LISTPRICE DOUBLE);